server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 529896519438-jumt7grsh6l8l6akctgiu9dmdampk0d4.apps.googleusercontent.com
            client-secret: Mh3IvBzmu_SBc58ZqrSxOpO8


